### ISSUE TITLE
denote.xyz Site Down

### ISSUE THREAD

**Issue by philmill** [egoist/denote#17]
I realize this isn't about the codebase, but I'm having difficulty finding a status update on social media regarding https://denote.xyz/ being down. I'm wondering how to fetch content for local storage. I don't have many notes there, but info on status would be helpful. 

Thanks

**Comment by egoist** [comment]
I've renewed the domain so it should be back up in a few minutes, by the way even if the site is gone forever you can still get you data since the data storage is managed by [blockstack.org](https://docs.blockstack.org/data-storage/overview).

**Comment by egoist** [comment]
It should work now.

**Comment by philmill** [comment]
Hey thanks. I've retrieved my data on another Blockstack app but it required my to dig into my browser for Auth keys. I probably should have looked while the site was down to see if I still had access. Thanks for the quick response and providing an easy way to store simple notes. Love the site.
